package com.example.uxn_api.web.error;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

@AllArgsConstructor
@Getter
public enum ErrorCode {
    NOT_FOUND(404,"NOT_FOUND","NOT_FOUND"),
    OVER_YEAR(410,"OVER_YEAR","PAGE NOT FOUND"),
    NOT_COMPLETE_SIGN_UP(411,"NOT_COMPLETE_SIGN_UP","INTER SERVER ERROR"),
    OVER_VERIFY_TIME_30(412,"OVER_VERIFY_TIME_30","EMAIL DUPLICATED"),
    NOT_COMPLETE_EMAIL_VERIFY(413,"NOT_COMPLETE_EMAIL_VERIFY","EMAIL DUPLICATED"),
    DUPLICATE_ACCOUNT(413,"NOT_COMPLETE_EMAIL_VERIFY","EMAIL DUPLICATED"),
    DUPLICATE_STAFF(413,"NOT_COMPLETE_EMAIL_VERIFY","EMAIL DUPLICATED"),

    BLOCKED_USER(416,"BLOCKED_USER","BLOCKED_USER"),

    INPUT_CODE_EMPTY(410,"INPUT_CODE_EMPTY","INPUT_CODE_EMPTY"),
    STAFF_NOT_FOUND(411,"STAFF_NOT_FOUND","STAFF_NOT_FOUND"),
    USER_NOT_FOUND(414,"USER_NOT_FOUND","USER_NOT_FOUND"),
    TARGET_NOT_FOUND(415,"TARGET_NOT_FOUND","TARGET_NOT_FOUND"),

    CHANGE_PASSWORD_TOKEN_ERROR(412,"CHANGE_PASSWORD_TOKEN_ERROR","CHANGE_PASSWORD_TOKEN_ERROR"),
    CHANGE_PASSWORD_EMAIL_ERROR(413,"CHANGE_PASSWORD_EMAIL_ERROR","CHANGE_PASSWORD_EMAIL_ERROR"),

    BEFORE_DONE(416,"BEFORE_DONE","BEFORE_DONE"),
    CODE_NOT_EQUAL(412,"INPUT_CODE_EMPTY","INPUT_CODE_EMPTY"),
    OVER_5_STAFF(405,"OVER_5_STAFF","OVER_5_STAFF");

    private int status;
    private String errorCode;
    private String message;


}
