package com.example.uxn_common.global.domain.user;

public enum ActivityKind {
    NONE,SIGN_UP_TRY,SIGN_UP_FAIL,TRY_LOGIN,LOGIN_FAIL,LOGIN_SUCCESS,
    NOTE_ADD,NOTE_DELETE,NOTE_UPDATE,
    CALIBRATION_ADD,CALIBRATION_DELETE,CALIBRATION_UPDATE,
    DATA_ADD,DATA_DELETE,DATA_UPDATE,
    REGISTER_STAFF,UN_REGISTER_STAFF,
    REGISTER_USER,UN_REGISTER_USER,
    SHOW_USER_LIST,SHOW_APPROVAL_USER_LIST,
    INVITE_USER,
    SEND_VERIFICATION_EMAIL,FIND_PASSWORD,
    CHANGE_PASSWORD
}
